
name: Tribblix

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/tribblix.yml'
      - '.github/workflows/testrun.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[testos=') || contains(github.event.head_commit.message, '[testos=tribblix]') }}
    strategy:
      fail-fast: false
      matrix:
        release: ["0m39", "0m40"]
        arch: [""]
        runs: ["ubuntu-24.04"]
        sync: [ "scp", "nfs", "rsync" ]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: tribblix
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: ${{ matrix.sync }}
